services:
  postgres:
    image: postgres:15-alpine
    container_name: resume_analyzer_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: resumeuser
      POSTGRES_PASSWORD: resumepass123
      POSTGRES_DB: resumedb
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5555:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U resumeuser -d resumedb" ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
